name: Andre Ferreira
# avatar: images/profile.png # Avatar image. Default to "images/profile.webp".
bio: 'Trader de Renda Fixa, Engenheiro.'
location: São Paulo, Brazil # HTML markup are supported, such as: <a href='https://www.openstreetmap.org/search?query=Earth'>Earth</a>.
# about: https://razonyang.com # The external about page. The internal about page will be used if not set.
params: {
  # layout: compact
}
social:
  email: colocar
  github: https://github.com/andrefpoli
  twitter: @YoloCap_
  patreon: nada
  paypal: nada
  rss: "" # Remove RSS
