email: colocar
#facebook: yourfacebookusername
github: github.com/andrefpoli
#gitlab: yourgitlabusername
linkedin: andre-ferreira-5941819a
#xing: yourxingusername
#stackoverflow: yourstackoverflowuserid
twitter: YoloCap_
#weibo: yourweibousername
#zhihu: yourzhihuusername
instagram: colocar
#quora: yourquorausername
#tumblr: yourtumblrusername
#reddit: yourredditusername
telegram: colocar
#qq: yourqqnumber
#dockerhub: yourdockerhubusername
#bitbucket: yourbitbucketworkspaceid
#kaggle: yourkaggleusername
medium: colocar # Medium username or custom domain(e.g. https://custom.domain.tld).
#lastfm: yourlastfmusername
#bilibili: yourbilibiliuserid
youtube: colocar
discord: colocar discord invite code
#discourse: https://yourforum.tld
#facebookgroup: yourfacebookgroupname
#tiktok: yourtiktokusername
#pinterest: yourpinterestusername
#mastodon: yourmastodonusername
#liberapay: yourliberapayaccount
#paypal: razonyang
patreon: colocar
tipeee: colocar
